# Generated by Django 3.2.6 on 2021-08-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_rename_desc_movie_descripction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descripction',
            new_name='description',
        ),
    ]
